# Project Information
site_name: 'stata_kernel'
site_description: 'A Jupyter Kernel for Stata. Works with Windows, macOS, and Linux.'
site_author: 'Kyle Barron'

docs_dir: 'src'
site_dir: 'html/mkdocs'

# Repository
repo_name: 'kylebarron/stata_kernel'
repo_url: 'https://github.com/kylebarron/stata_kernel'
edit_uri: 'blob/master/docs/src/'
site_url: 'https://kylebarron.github.io/stata_kernel/'

# Social links
extra:
  social:
    - type: 'github'
      link: 'https://github.com/kylebarron'
    - type: 'key'
      link: 'https://keybase.io/kylebarron'

# Layout
nav:
    - Home: 'index.md'
    - Getting Started: 'getting_started.md'
    - Using Jupyter:
        - Introduction: 'using_jupyter/intro.md'
        - Jupyter Notebook: 'using_jupyter/notebook.md'
        - Atom: 'using_jupyter/atom.md'
        - JupyterLab: 'using_jupyter/lab.md'
        - Jupyter QtConsole: 'using_jupyter/qtconsole.md'
        - Jupyter Console: 'using_jupyter/console.md'
        # - Using Jupyter on Remote Servers: 'using_jupyter/remote.md'
    - Using the Stata Kernel: using_stata_kernel/magics.md
        # - Introduction: 'using_stata_kernel/intro.md'
        # - Magics: 'using_stata_kernel/magics.md'
    - Troubleshooting: 'troubleshooting.md'
    - Comparison with ipystata: 'comparison_with_ipystata.md'
    - Addendum: 'addendum.md'
    - License: 'license.md'


# Theme
theme:
    feature:
        tabs: false
    logo:
        icon: 'home'
    name: 'material'
    language: 'en'
    palette:
        primary: 'blue'
        accent:  'light blue'
    font:
        text: 'Nunito Sans'
        code: 'Fira Code'

extra_javascript:
    - helpers/helpers.js
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# These extensions are chosen to be a superset of Pandoc's Markdown.
# This way, I can write in Pandoc's Markdown and have it be supported here.
# https://pandoc.org/MANUAL.html
markdown_extensions:
    - admonition
    - attr_list
    - codehilite:
        guess_lang: false
    - def_list
    - footnotes
    - pymdownx.arithmatex
    - pymdownx.betterem
    - pymdownx.caret:
        insert: false
    - pymdownx.details
    - pymdownx.escapeall:
        hardbreak: true
        nbsp: true
    - pymdownx.magiclink:
        hide_protocol: true
        repo_url_shortener: true
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist(custom_checkbox=true)
    - pymdownx.tilde
    - toc:
        permalink: true
